version: '3.3'
services:
    app:
        build:
          context: .
        volumes:
            - ./credentials:/app/credentials
            - ./instances:/app/instances
            - ./logs:/app/logs
            - ./maps:/app/maps
        environment:
            - RPP_DISCORD_CLIENT_ID
            - RPP_DISCORD_TOKEN
        container_name: rpp
